### ISSUE TITLE
minSdkVersion 15 cannot be smaller than version declared in library

### ISSUE THREAD

**Issue by hasnain-ahmad** [amanjeetsingh150/ImageZipper#2]
Hi,

I am compiling ImageZipper library in my project. I have minSdkVersion is 15 in my build.gradle but in library the minSdkVersion is 19. I am getting the following error. Please guide on this issue. 

> Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared in library [com.github.amanjeetsingh150:ImageZipper:1.3] C:\Users\Hasnain\.gradle\caches\transforms-1\files-1.1\ImageZipper-1.3.aar\974c88ab40b03cd19c606cb3bed9f887\AndroidManifest.xml as the library might be using APIs not available in 15
>   	Suggestion: use a compatible library with a minSdk of at most 15,
>   		or increase this project's minSdk version to at least 19,
>   		or use tools:overrideLibrary="com.developers.imagezipper" to force usage (may lead to runtime failures)

**Comment by amanjeetsingh150** [comment]
Hey @hasnain-ahmad ,
This is basically because my library has min SDK of 19 and thus on merging of Manifests these conflicts are occurring. So for this you can have two kinds of approach:
1. Either mention tools:overrideLibrary="com.developers.imagezipper" in your Manifest which will force override. But in this case there may be some runtime error which can occur.
2. Download my library as a zip or clone it add it as module and change the min SDK version in the library's manifest file.
Do revert me if any more help needed in any case.

**Comment by hasnain-ahmad** [comment]
I apply the 2nd one solution. 
Issue Resolved

**Comment by amanjeetsingh150** [comment]
Do tell me for any further help :+1:
